### ISSUE TITLE
[question] ubuntu hyprland installation

### ISSUE THREAD

**Issue by iharh** [ipg0/dotfiles-hypr#1]
Could you suggest a way to install hyprland to ubuntu/rhino (not a debian) OS?

**Comment by ipg0** [comment]
@iharh I used this guide. It's a bit outdated, requires building / installing some other packages and the latest couple versions of Hyprland aren't compilable (without breaking dpkg dependencies for a lot of stuff). I'm currently not at home, so if you need me to check precisely which version I'm running, let me know.

https://gist.github.com/Vertecedoc4545/3b077301299c20c5b9b4db00f4ca6000

**Comment by iharh** [comment]
Thank you very much, @ipg0 . Let me start from that!
